[package]
name = "bezier_curve"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = { version = "0.23.0", features = ["persistence"] }
egui_plot = "0.23.0"
eframe = { version = "0.23.0", features = ["persistence"] }
serde = "1.0"
serde_derive = "1.0"
